services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_api_biblioteca
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres_api_biblioteca
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql