services:
  - type: web
    name: api-biblioteca
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma migrate deploy && npm run dist
    startCommand: npm run start:dist
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false